using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace AAPakFile.Editing;

/// <summary>
/// An <see cref="ObservableCollection{T}"/> that supports deferring
/// <see cref="INotifyCollectionChanged.CollectionChanged"/> notifications.
/// </summary>
/// <remarks>
/// <para>
/// While any deferral scope (opened via <see cref="DeferNotifications"/>) is active,
/// individual <see cref="NotifyCollectionChangedEventArgs"/> are buffered rather than
/// forwarded to subscribers. When the outermost scope is disposed, all buffered events
/// are replayed in order. Deferral scopes are ref-counted — nested scopes are safe.
/// </para>
/// <para>
/// If no mutations occur inside a deferral scope, no event is fired on dispose.
/// <see cref="NotifyCollectionChangedAction.Reset"/> is never generated by this class;
/// callers always receive the exact sequence of targeted add / remove / replace events.
/// </para>
/// </remarks>
internal sealed class DeferrableObservableCollection<T> : ObservableCollection<T>
{
    private int _deferDepth;
    private List<NotifyCollectionChangedEventArgs>? _pendingEvents;

    public DeferrableObservableCollection() { }

    public DeferrableObservableCollection(IEnumerable<T> items) : base(items) { }

    /// <summary>
    /// Begins a deferral scope. Returns an <see cref="IDisposable"/> that ends the scope
    /// when disposed. Nested calls are ref-counted; events are replayed only when the
    /// outermost scope is disposed.
    /// </summary>
    public IDisposable DeferNotifications()
    {
        if (_deferDepth == 0)
            _pendingEvents = [];
        _deferDepth++;
        return new DeferScope(this);
    }

    /// <inheritdoc/>
    protected override void OnCollectionChanged(NotifyCollectionChangedEventArgs e)
    {
        if (_deferDepth > 0)
            _pendingEvents!.Add(e);
        else
            base.OnCollectionChanged(e);
    }

    private void EndDefer()
    {
        _deferDepth--;
        if (_deferDepth > 0)
            return;

        var events = _pendingEvents;
        _pendingEvents = null;

        if (events is { Count: > 0 })
        {
            foreach (var e in events)
                base.OnCollectionChanged(e);
        }
    }

    private sealed class DeferScope(DeferrableObservableCollection<T> owner) : IDisposable
    {
        private bool _disposed;

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            owner.EndDefer();
        }
    }
}